# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='The UUID is is set from "outside"/client when ingesting a fingerprint', unique=True),
        ),
    ]
