# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fprint', '0002_auto_20170603_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='index_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
