# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fprint', '0003_entry_index_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='entry',
            name='artist_name',
            field=models.CharField(blank=True, db_index=True, help_text='Normalised to ASCII', max_length=256, null=True, verbose_name='Artist Name'),
        ),
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.DurationField(db_index=True, help_text='Duration in seconds (float)', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Normalised to ASCII', max_length=256, null=True, verbose_name='Track Name/Title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.TextField(help_text='Echoprint code string, compressed', null=True),
        ),
    ]
